-- PUBLIC.TBL_FTP_USER definition

CREATE CACHED EXISTS NOT TABLE "PUBLIC"."TBL_FTP_USER"(
    "USERID" VARCHAR_IGNORECASE(255) NOT NULL,
    "USERPASSWORD" VARCHAR_IGNORECASE(255),
    "HOMEDIRECTORY" VARCHAR_IGNORECASE(255),
    "ENABLEFLAG" BOOLEAN DEFAULT TRUE,
    "WRITEPERMISSION" BOOLEAN DEFAULT TRUE,
    "IDLETIME" INTEGER,
    "UPLOADRATE" INTEGER,
    "DOWNLOADRATE" INTEGER,
    "MAXLOGINNUMBER" INTEGER,
    "MAXLOGINPERIP" INTEGER
);